### PR TITLE
rainbowhat - Update README.md

### PR DESCRIPTION
**Pull request by adkl**
- Register Bmx280 temperature sensor before registering dynamic sensor callback

Based on my experience and also a discussion from https://github.com/androidthings/contrib-drivers/issues/103, maybe it should be useful to state this important block of code in the docs.

### CODE REVIEW

**Comment by adkl** [comment]
@googlebot I signed it!

**Comment by devunwired** [comment]
Thanks for noticing this.
We need to separate the blocks of code a bit more, as these two things are not necessarily expected to happen in the same scope (see the example above it for input drivers). There should be a separate block for the code you added with a comment about registering the listener in your activity.

**Review by devunwired — CHANGES_REQUESTED** [review]
Thanks for noticing this.
We need to separate the blocks of code a bit more, as these two things are not necessarily expected to happen in the same scope (see the example above it for input drivers). There should be a separate block for the code you added with a comment about registering the listener in your activity.

**Comment by adkl** [comment]
I agree, now it looks more convenient.

**Review by devunwired — APPROVED** [review]

**Pull request merged**
