### PR TITLE
Outputdrive, led emite event, action futuro

### PR DESCRIPTION
**Pull request by diegoferreiracaetano**
Hello I'm sending this pull request, to contribute with the android things, with these drive we can capture event of the led so during stay running for a while.

### CODE REVIEW

**Comment by diegoferreiracaetano** [comment]
I signed it!

**Comment by diegoferreiracaetano** [comment]
Yes, the intention is to perform actions after the led run a few times, or when a time comes to an end.

**Comment by jdkoren** [comment]
@diegoferreiracaetano My point is, you don't need a driver for this, nor does it make sense.

The purpose of an `InputDriver` is to provide a signal from something you don't control, like a physical button, which is controlled by the user who is pressing it (or not). In that case, there is input coming from an external source.

Here, you have only output because you control the GPIO value from within the app. If you just want to run some code when the value changes, then you can simply use a [`GpioCallback`](https://developer.android.com/things/reference/com/google/android/things/pio/Gpio.html#registerGpioCallback(com.google.android.things.pio.GpioCallback)). If you want to run some code after a timeout, simply use `Handler.postDelayed()` in your code.

**Comment by diegoferreiracaetano** [comment]
Got it.

Actually, it's a helper for output.
Where you can abstract some operations.

Here's an example:
https://github.com/diegoferreiracaetano/sample-output

**Comment by jdkoren** [comment]
> Actually, it's a helper for output. Where you can abstract some operations.

You've abstracted posting `Runnable`s to `Handler`s, and calling `gpio.setValue()`. I do not think anyone needs a library for this.

**Pull request closed without merging**
