### PR TITLE
MCP23017 driver

### PR DESCRIPTION
**Pull request by jenchenUA**
Adds support of IO expander MCP23017

### CODE REVIEW

**Comment by jenchenUA** [comment]
I signed it!

**Comment by jenchenUA** [comment]
I signed it!

**Comment by Fleker** [comment]
Thanks for submitting this PR. We are not accepting new drivers in this repo, but you're free to publish it on your own and then [submit the driver](https://androidthings.withgoogle.com/submit-a-driver/#!/).

**Comment by jenchenUA** [comment]
The driver is available in the self [repository](https://github.com/jenchenUA/MCP23017-Android-Things-Driver)

**Pull request closed without merging**
